version: '3.3'

services:
  goals-frontend:
    image: goals-frontend:1.0.0
    container_name: goals-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - goals-net
    ports:
      - 3000:80
    env_file:
      - .env

networks:
  goals-net:
    driver: bridge

volumes:
  dbdata:
